create table if not exists public.repository_security_policies (
  user_id uuid not null,
  repository text not null check (repository ~ '^[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+$'),
  enforcement_mode text not null default 'monitor' check (enforcement_mode in ('monitor', 'block')),
  block_at text not null default 'high' check (block_at in ('high', 'medium', 'notice')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (user_id, repository)
);

create table if not exists public.finding_suppressions (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  repository text not null check (repository ~ '^[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+$'),
  finding_id text not null check (finding_id ~ '^[A-Za-z0-9_-]{1,40}$'),
  disposition text not null check (disposition in ('accepted_risk', 'false_positive', 'temporary')),
  reason text not null check (char_length(reason) between 5 and 500),
  expires_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, repository, finding_id)
);

create index if not exists finding_suppressions_lookup_idx
  on public.finding_suppressions (user_id, repository, finding_id);

alter table public.repository_security_policies enable row level security;
alter table public.finding_suppressions enable row level security;
revoke all on public.repository_security_policies from anon, authenticated;
revoke all on public.finding_suppressions from anon, authenticated;

comment on table public.repository_security_policies is
  'Server-managed per-repository monitor/block thresholds for GitHub checks.';
comment on table public.finding_suppressions is
  'Server-managed, auditable finding dispositions. Source code is never stored.';
